### PR TITLE
readme files added/edited

### PR DESCRIPTION
**Pull request by aydinsenih**

### CODE REVIEW

**Review by crystal-csete — APPROVED** [review]
These files have great notes inside them explaining what the code does. Great job!

**Review by JusticeMatthew — APPROVED** [review]
Looks amazing!

**Review by c-melchor — APPROVED** [review]
Looks great, nice job!

**Review by cmirza — APPROVED** [review]
Nice descriptive readme

**Review by reesharper — APPROVED** [review]
Wow, this looks amazing! A very difficult task to do thoroughly. Great work!

**Pull request merged**
