### PR TITLE
New documentation implemented

### PR DESCRIPTION
**Pull request by aydinsenih**
Documentation separated different files

### CODE REVIEW

**Review by crystal-csete — APPROVED** [review]
This documentation looks great!

**Review by c-melchor — APPROVED** [review]
Awesome, thanks for putting this together.

**Review by JusticeMatthew — APPROVED** [review]
THANKS FOR UPDATING THE DOCS I LOVE DOCS THANK YOU

**Review by ndossett — APPROVED** [review]
Thank you for putting these together. Should be very helpful for the incoming cohort!

**Pull request merged**
