### PR TITLE
Feature/auth middleware

### PR DESCRIPTION
**Pull request by c-melchor**
- This code adds auth middleware to endpoints
- Only error found is with upload functionality, which Matthew said he is currently working on
- I changed the linting errors, but still wants me to add semicolon after .then(), which will break code

### CODE REVIEW

**Comment by c-melchor** [comment]
Had to comment out unfinished PUT request, still in the works

**Review by crystal-csete — APPROVED** [review]
I am glad you got the authorization for the endpoints working.

**Review by cmirza — APPROVED** [review]
Good update, secures end points. Changes are simple and clean.

**Review by reesharper — APPROVED** [review]
Love the use of the route.use('/' authRequired)!

**Pull request merged**
