### PR TITLE
Cases table and seed overhaul

### PR DESCRIPTION
**Pull request by JusticeMatthew**
The cases table and seeds have been updated to the new data structure

These changes will require you to reset your local DB then migrate and reseed

### CODE REVIEW

**Review by c-melchor — APPROVED** [review]
I'm excited for the next cohort to get these tables 😀 , so much better!

**Review by crystal-csete — APPROVED** [review]
It will be nice to have updated tables.

**Review by reesharper — APPROVED** [review]
Lots of great condensing of code, looks much cleaner!

**Review by cmirza — APPROVED** [review]
Nice updates to the backend!

**Review by ruizaj13 — APPROVED** [review]
Nothing better than a clean and proper database, thank you

**Pull request merged**
